services:
  app:
    container_name: news-portal
    image: news-portal
    build:
      context: .
    depends_on:
      - db
  db:
    image: postgres:15.1
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: news_portal
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres


volumes:
  postgres: