services:
  postgres:
    image: 'postgres:15.1'
    container_name: 'postgres'
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_ROOT_PASSWORD: 1234
      POSTGRES_DATABASE: news_portal
      PGDATA: /data/postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - apinetwork
    volumes:
      - ./postgresql/:/var/lib/postgresql/data/

  app:
    container_name: 'news-portal'
    image: news-portal
    build:
      context: .
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/news-portal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - postgres
    networks:
      - apinetwork

networks:
  apinetwork:
    driver: bridge

