services:
  postgresqldb:
    image: 'postgres:14.7'
    container_name: postgresqldb
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_ROOT_PASSWORD: 1234
      POSTGRES_DB: news_portal
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust

    volumes:
      - .:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - apinetwork

  app:
    container_name: 'news-portal'
    image: news-portal
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresqldb:5432/news_portal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: '1234'
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    depends_on:
      - postgresqldb
    networks:
      - apinetwork

networks:
  apinetwork:

    driver: bridge

