locale:
  default: en
  paramName: locale

  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: validate
      generate-ddl: false

  datasource:
    url: jdbc:postgresql://localhost:5432/news_portal
    username: postgres
    password: 1234
  flyway:
    url: jdbc:postgresql://localhost:5432/news_portal
    locations: /db
    enabled: true
    password: 1234
    schemas: public
    user: postgres
    encoding: UTF-8
server:
  port: 8080







